name: Kafka Sink CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Compile, test and create package
        run: mvn -B clean verify package
      - name: Coverage report
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/**/target/reports/jacoco.xml
          token: ${{ github.token }}
          title: Code Coverage
          update-comment: true
          min-coverage-overall: 40
          min-coverage-changed-files: 70
          pass-emoji: ':white_check_mark:'
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: target

  image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging


#  func-test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Build the Docker image
#        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
#      - uses: actions/upload-artifact@v4
#        with:
#          name: Package
#          path: staging
