name: Release

on:
  push:
    tags:
      - '*'

jobs:
  trigger-release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trigger build
        run: |
          /bin/bash -c "curl https://new-jenkins.ontotext.com/generic-webhook-trigger/invoke?token=${{ secrets.JenkinsTrigger }}&pipeline_branch=main&kafka_sink_tag=${GITHUB_REF#refs/*/}"

